---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ac3.redhat.com
  resources:
  - ac3networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ac3.redhat.com
  resources:
  - ac3networks/finalizers
  verbs:
  - update
- apiGroups:
  - ac3.redhat.com
  resources:
  - ac3networks/status
  verbs:
  - get
  - patch
  - update
